# Exported from Render on 2024-09-22T04:49:19Z
services:
- type: web
  name: trellobackend
  runtime: node
  repo: https://github.com/Sah314/trellobackend
  plan: free
  envVars:
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: yarn install && yarn build
  startCommand: npx prisma generate && yarn start
version: "1"
